name: Update Related Team Issues

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:      # Allows manual triggering from GitHub

jobs:
  update-related-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Use GitHub script to update issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = "GovAlta";
            const communityRepo = "design-system-backlog";
            const teamRepo = "ui-components";

            // Helper to get type
            function getTypeFromIssue(issue) {
              if (issue?.type && typeof issue.type === 'object' && issue.type.name) {
                return issue.type.name.toLowerCase();
              }
              if (issue?.issue_type && typeof issue.issue_type === 'object' && issue.issue_type.name) {
                return issue.issue_type.name.toLowerCase();
              }
              return 'other';
            }

            // Get all open issues in the community backlog
            const communityIssues = await github.paginate(
              github.rest.issues.listForRepo,
              { owner, repo: communityRepo, state: "open" }
            );

            for (const communityIssue of communityIssues) {
              const componentName = communityIssue.title.trim();

              // Get OPEN issues in team backlog
              const openIssues = await github.paginate(
                github.rest.issues.listForRepo,
                {
                  owner,
                  repo: teamRepo,
                  labels: componentName,
                  state: "open"
                }
              );

              // Get CLOSED issues in team backlog
              const closedIssues = await github.paginate(
                github.rest.issues.listForRepo,
                {
                  owner,
                  repo: teamRepo,
                  labels: componentName,
                  state: "closed"
                }
              );

              // Format open issues list
              const openList = openIssues.length > 0
                ? openIssues.map(issue => {
                    const type = getTypeFromIssue(issue);
                    return `- [#${issue.number}](${issue.html_url}) (${type}) ${issue.title}`;
                  }).join('\n')
                : "_No related issues found._";

              // Format closed issues list
              const closedList = closedIssues.length > 0
                ? closedIssues.map(issue => {
                    const type = getTypeFromIssue(issue);
                    return `- [#${issue.number}](${issue.html_url}) (${type}) ${issue.title}`;
                  }).join('\n')
                : "_No closed issues._";

              // Wrap both in comment tags so we can safely replace them
              const relatedSection = `### Open issues\n${openList}`;
              const closedSection = `#### Closed issues\n${closedList}`;
              const combinedSection = `<!-- related-issues-start -->\n${relatedSection}\n\n${closedSection}\n<!-- related-issues-end -->`;

              // One-time cleanup regex: remove any old heading blocks that resemble previous formats
              const sectionRegex = /(<!-- related-issues-start -->[\s\S]*?<!-- related-issues-end -->|## Related issues[\s\S]*?(?=## |### |$)|### Open issues[\s\S]*?(?=## |### |$))/gi;

              let updatedBody = communityIssue.body || "";
              if (sectionRegex.test(updatedBody)) {
                updatedBody = updatedBody.replace(sectionRegex, combinedSection);
              } else {
                updatedBody += `\n\n${combinedSection}`;
              }

              // Update the community issue with the new body
              await github.rest.issues.update({
                owner,
                repo: communityRepo,
                issue_number: communityIssue.number,
                body: updatedBody
              });

              console.log(`✅ Cleaned and updated: ${componentName}`);
            }
